# Dockerfile-mysql-init
# Use Google Jib base image
FROM gcr.io/distroless/java:8

# Copy initialization script
COPY init.sql /docker-entrypoint-initdb.d/

# Environment variables for MySQL root user and password
ENV MYSQL_ROOT_USER=root
ENV MYSQL_ROOT_PASSWORD=root
