version: '3'

services:

  loopdfs:
    image: "smunyao/loopdfs:v2"
    container_name: "loopdfs_service"
    ports:
      - 8080:8080
    networks:
      - smunyao
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loopdfs
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    image: "mysql:latest"
    container_name: "loopdfs_mysql"
    ports:
      - 3307:3306
    networks:
      - smunyao
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loopdfs

    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  smunyao:
    driver: "bridge"
